databases:
  - name: gre-vocab-cheap
    plan: free
    databaseName: gredbname
    user: gre_vocab_user

services:
  - type: web
    name: gre-vocab-master
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 2 --threads 2
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        value: https://gre-vocab.onrender.com/auth/callback
